#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_nginx

ynh_nodejs_install

ynh_config_add_systemd

yunohost service add $app --description="Peer-to-peer file transfers" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL FILEPIZZA
#=================================================
ynh_script_progression "Installing the app..."

pushd $install_dir
    ynh_hide_warnings corepack enable && corepack prepare pnpm@latest --activate
    ynh_hide_warnings pnpm install
    ynh_hide_warnings pnpm run build
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
